config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[index show]

  namespace :admin do
    resources :posts do
      member do
        patch :publish
        patch :unpublish
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id            :bigint           not null, primary key
#  email         :citext           not null
#  password_hash :string
#  status        :integer          default("unverified"), not null
#
# Indexes
#
#  index_accounts_on_email  (email) UNIQUE WHERE (status = ANY (ARRAY[1, 2]))
#
class Account < ApplicationRecord
  include Rodauth::Rails.model(:admin)

  enum :status, { unverified: 1, verified: 2, closed: 3 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :bigint           not null, primary key
#  body            :text
#  body_updated_at :datetime
#  published_at    :datetime
#  ref             :string           not null
#  summary         :text
#  title           :string
#  visitor_count   :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_posts_on_published_at  (published_at)
#  index_posts_on_ref           (ref) UNIQUE
#
class Post < ApplicationRecord
  before_validation :generate_ref, unless: :persisted?
  before_save :handle_body_change

  scope :published, -> { where.not(published_at: nil) }

  validates :title, :summary, :body, presence: true, if: :published?
  validates :published_at, comparison: {
    less_than_or_equal_to: -> { Time.current },
    message: "cannot be in the future"
  }, allow_nil: true
  validates :ref, presence: true, uniqueness: true
  validates :visitor_count, numericality: { greater_than_or_equal_to: 0 }

  def published?
    published_at.present?
  end

  def publish
    update(published_at: Time.current)
  end

  def unpublish
    update(published_at: nil)
  end

  def visited!
    increment!(:visitor_count)
  end

  private

  def generate_ref
    self.ref ||= Random.hex(16)
  end

  def handle_body_change
    return unless body_changed?

    self.body_updated_at = Time.current
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy publish unpublish ]

    # GET /posts or /posts.json
    def index
      @posts = Post.all
    end

    # GET /posts/1 or /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts or /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html {
            redirect_to admin_post_path(@post), notice: "Post was successfully created."
          }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html {
            redirect_to admin_post_path(@post), notice: "Post was successfully updated."
          }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy!

      respond_to do |format|
        format.html {
          redirect_to admin_posts_path, status: :see_other, notice: "Post got destroyed."
        }
      end
    end

    def publish
      if @post.published? || @post.publish
        redirect_to admin_posts_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def unpublish
      @post.unpublish if @post.published?

      redirect_to admin_posts_path
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.expect(post: %i[title summary body])
      end
  end
end

app/controllers/admin/rodauth_controller.rb
module Admin
  class RodauthController < ApplicationController
    # Used by Rodauth for rendering views, CSRF protection, running any
    # registered action callbacks and rescue handlers, instrumentation etc.

    # Controller callbacks and rescue handlers will run around Rodauth endpoints.
    # before_action :verify_captcha, only: :login, if: -> { request.post? }
    # rescue_from("SomeError") { |exception| ... }

    # Layout can be changed for all Rodauth pages or only certain pages.
    # layout "authentication"
    # layout -> do
    #   case rodauth.current_route
    #   when :login, :create_account, :verify_account, :verify_account_resend,
    #        :reset_password, :reset_password_request
    #     "authentication"
    #   else
    #     "application"
    #   end
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.published
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.visited!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))

      raise ActiveRecord::RecordNotFound unless @post.published?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def md(text)
    markdown.render(text).html_safe
  end

  private

  def markdown
    @markdown ||= Redcarpet::Markdown.new(renderer, fenced_code_blocks: true)
  end

  class CustomRenderer < Redcarpet::Render::HTML
    def header(header, header_level)
      case header_level
      when 1
        %(<h1 class="my-5 text-5xl">#{header}</h1>)
      when 2
        %(<h2 class="my-3 text-4xl">#{header}</h2>)
      else
        super
      end
    end

    def block_code(code, language)
      %(<pre class="
          my-5 border-solid border-2 border-nord8 rounded-md shadow-md
          shadow-nord8"
        ><code class="language-#{language}">#{code}</code></pre>)
    end

    def codespan(code)
      %(<code class="text-nord9">#{code}</code>)
    end

    def link(link, title, content)
      %(<a href="#{link}" target="_blank" class="
          border-r border-b px-2 ml-px hover:border hover:border-nord8
          hover:m-0"
        >#{content}</a>)
    end
  end

  def renderer
    @renderer ||= CustomRenderer.new(
      autolink: true,
      filter_html: true,
      with_toc_data: true
    )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_with(model: [:admin, post], class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-nord11 text-nord4 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border outline-none bg-nord6 text-nord3 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :summary %>
    <%= form.textarea :summary, rows: 4, class: "block shadow rounded-md border outline-none bg-nord6 text-nord3 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.textarea :body, rows: 4, class: "block shadow rounded-md border outline-none bg-nord6 text-nord3 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/admin/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= post.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Published at:</strong>
    <%= post.published_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Summary:</strong>
    <%= post.summary %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= md(post.body) %>
  </p>

</div>

app/views/admin/posts/_post_card.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= post.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Summary:</strong>
    <%= post.summary %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Published at:</strong>
    <%= post.published_at %>
  </p>

</div>

app/views/admin/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", admin_post_path(@post), class: "button" %>
  <%= link_to "Back to posts", admin_posts_path, class: "button" %>
</div>

app/views/admin/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 mb-5 bg-nord14 text-nord3 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Posts" %>

  <p>
    <%= link_to "New post", new_admin_post_path, class: "button" %>
  </p>
  <div id="posts" class="min-w-full">
    <% @posts.each do |post| %>
      <%= render "post_card", post: post %>
      <div class="flex flex-row">
        <p>
          <%= link_to "Show", admin_post_path(post), class: "mx-1 button" %>
        </p>
        <p>
          <%= link_to "Edit", edit_admin_post_path(post), class: "mx-1 button" %>
        </p>
        <% if post.published? %>
          <%= button_to "Unpublish", unpublish_admin_post_path(post), method: :patch, class: "mx-1 button" %>
        <% else %>
          <%= button_to "Publish", publish_admin_post_path(post), method: :patch, class: "mx-1 button" %>
        <% end %>
        <%= button_to "Destroy", admin_post_path(post), method: :delete, class: "mx-1 button-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", admin_posts_path, class: "button" %>
</div>

app/views/admin/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 mb-5 bg-nord14 text-nord3 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "admin/posts/post", post: @post %>

    <div class="mt-5">
      <%= link_to "Edit this post", edit_admin_post_path(@post), class: "button" %>
      <%= link_to "Back to posts", admin_posts_path, class: "button" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this post", admin_post_path(@post), method: :delete, class: "button-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<nav class="container bg-nord0 h-20 mx-auto px-4 flex flex-row items-center justify-between border-b-2 border-nord4">
  <div class="min-w-fit text-nowrap flex flex-row items-center">
    <%= link_to "Did Llamas Know", root_path, class: "text-5xl px-4 py-2 text-nowrap" %>
    <%= inline_svg_tag 'llama_icon.svg', height: '48px', width: '48px' %>
  </div>
  <div class="text-3xl px-8">
    <%= link_to "Blog", posts_path %>
  </div>
</nav>

app/views/application/_sidebar.html.erb
  <aside id="sidebar" class="w-1/4 hidden md:flex flex-col items-center">
    <h1 class="text-2xl my-4">Welcome!</h1>
    <p class="my-2">
      Welcome to my development blog. I plan to write about various topics related to multiple technologies.
      (Mainly Ruby on Rails and NixOS in the beginning.) Look around in the posts on the home page.
    </p>
    <p>
      <strong>Note:</strong> The website's name is not related to Meta's <code>llama</code> AI models in any way.
    </p>
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DLK | <%= content_for(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/nord.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
    <!-- and it's easy to individually load additional languages -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/ruby.min.js"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-nord0 text-nord4">
    <%= render "navbar" %>

    <div class="container mx-auto mt-8 max-sm:px-2 sm:px-5 flex">
      <main class="w-full md:w-3/4 text-xl">
        <%= yield %>
      </main>

      <%= render "sidebar" %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="flex flex-col items-center">
  <h1 class="my-5 text-6xl">
    <%= post.title %>
  </h1>

  <%= render "posts/timestamps", post: post %>

  <div class="my-5">
    <%= md(post.body) %>
  </div>
</div>

app/views/posts/_post_card.html.erb
<div id="<%= dom_id post %>" class="bg-nord1 rounded-md flex flex-col items-center p-4">
  <h1 class="text-2xl mb-2">
    <%= post.title %>
  </h1>

  <%= render "posts/timestamps", post: post %>

  <p class="my-5 text-justify">
    <%= post.summary %>
  </p>

  <p>
    <%= link_to "Read more", post, class: "button" %>
  </p>
</div>

app/views/posts/_post_timestamps.html.erb
<div class="text-xs self-start">
  <strong>Published at:</strong>
  <span><%= post.published_at.to_formatted_s(:date_only) %></span>
  <% if post.published_at + 1.day < post.body_updated_at %>
    <strong class="ml-4">Last update:</strong>
    <span><%= post.body_updated_at.to_formatted_s(:date_only) %></span>
  <% end %>
</div>

app/views/posts/_timestamps.html.erb
<div class="text-sm self-start">
  <strong>Published at:</strong>
  <span><%= post.published_at.to_formatted_s(:date_only) %></span>
  <% if post.published_at + 1.day < post.body_updated_at %>
    <strong class="ml-4">Last update:</strong>
    <span><%= post.body_updated_at.to_formatted_s(:date_only) %></span>
  <% end %>
</div>

app/views/posts/index.html.erb
<div>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Posts" %>

  <div class="flex flex-row">
    <div id="posts" class="px-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 items-start">
      <% @posts.each do |post| %>
        <%= render "post_card", post: post %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="mx-auto md:w-2/3 w-full px-4 sm:px-0 flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= link_to "Back to posts", posts_path, class: "button" %>

    <%= render @post %>
  </div>
</div>